### ISSUE TITLE
katanalibs is broken in kdelibs/kdecore/config/ksettings.h

### ISSUE THREAD

**Issue by FredBezies** [fluxer/kdelibs#2] opened 2020-01-29 12:35 UTC
Tried to build katanalibs, but it is broken really early...

```
[  1%] Building CXX object kdecore/CMakeFiles/kdecore.dir/kdecore_autogen/mocs_compilation.cpp.o
In file included from /home/fred/katana/packaging/archlinux/katanalibs/src/build/kdecore/kdecore_autogen/IJHAR2IVER/moc_ksettings.cpp:9,
                 from /home/fred/katana/packaging/archlinux/katanalibs/src/build/kdecore/kdecore_autogen/mocs_compilation.cpp:8:
/home/fred/katana/packaging/archlinux/katanalibs/src/kdelibs/kdecore/config/ksettings.h:64:76: error: 'Q_NULLPTR' was not declared in this scope
   64 | ttings(const QString &file, const OpenFlags mode, QObject *parent = Q_NULLPTR);
      |                                                                     ^~~~~~~~~

make[2]: *** [kdecore/CMakeFiles/kdecore.dir/build.make:75: kdecore/CMakeFiles/kdecore.dir/kdecore_autogen/mocs_compilation.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:3046: kdecore/CMakeFiles/kdecore.dir/all] Error 2
make: *** [Makefile:163: all] Error 2
```

**Comment by FredBezies** [comment] 2020-01-29 12:37
Related to this commit I think: https://github.com/fluxer/kdelibs/commit/2fa84d58bed71090adc22506806d5900fecfc7b2#diff-ff94c1cc9693543df9667110483162f6

**Comment by fluxer** [comment] 2020-01-29 13:06
Hi,

You are correct. Fixed via https://github.com/fluxer/kdelibs/commit/49744946c6675645f15d4d8d0e9f1dd2f85237f2. Thanks for reporting the issue!

Cheers!

**Comment by FredBezies** [comment] 2020-01-29 13:15
You're welcome. Trying to get it build once again. Let's hope no more bug report on it!

**Comment by fluxer** [comment] 2020-01-29 13:21
Should be ok, I build it pretty much daily but I use Katie instead of Qt4 which unfortunetly means there are compatibility issues with Qt4 from time to time.

**Comment by FredBezies** [comment] 2020-01-29 13:28
Is Katie working for every single component, now? Could be a great test to do... And modify PKGBUILD to use Katie instead of Qt4...

**Comment by fluxer** [comment] 2020-01-29 13:37
Theree are no major issues with Katie except with a minor one with the demarshaller of complex D-Bus types (e.g. [QVariantMapMap](https://github.com/fluxer/kdelibs/blob/master/solid/solid/backends/udisks2/udisks2.h#L33)) which can cause crashes with device managers, e.g. attempt to mount device from Dolphin can crash not only Dolphin but other applications too, but I am working on it.

It is regression since the last release candidate and that's why I have not released another one yet, as soon as it is fixed there will be new release candidate.

**Comment by FredBezies** [comment] 2020-01-29 13:50
OK. As you're providing git packages, let's go and use katie instead of QT4 :)

Will update needed PKGBUILD when there will be OK.

**Comment by fluxer** [comment] 2020-01-29 13:53
Yes, I intend to provide as many packages as possible for each release. I recommend that you use rc17 for now until the next release.

**Comment by FredBezies** [comment] 2020-01-29 13:56
Well, something is broken when using katie in katanalibs PKGBUILD:

```
-- Detecting CXX compile features - done
CMake Deprecation Warning at cmake/modules/FindKDE4Internal.cmake:235 (cmake_policy):
  The OLD behavior for policy CMP0000 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:32 (find_package)


CMake Deprecation Warning at cmake/modules/FindKDE4Internal.cmake:237 (cmake_policy):
  The OLD behavior for policy CMP0003 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:32 (find_package)


CMake Deprecation Warning at cmake/modules/FindKDE4Internal.cmake:240 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  CMakeLists.txt:32 (find_package)


CMake Error at /usr/share/cmake-3.16/Modules/FindQt4.cmake:1314 (message):
  Found unsuitable Qt version "5.14.1" from /usr/bin/qmake, this code
  requires Qt 4.x
Call Stack (most recent call first):
  cmake/modules/FindKDE4Internal.cmake:290 (find_package)
  CMakeLists.txt:32 (find_package)


-- Configuring incomplete, errors occurred!
```

**Comment by fluxer** [comment] 2020-01-29 14:05
Katana does not provide the FindQt4 CMake module and it is looking for `qmake` first which points to Qt5 version of it on your host.

To build with Katie there is [option](https://github.com/fluxer/kdelibs/blob/master/cmake/modules/FindKDE4Internal.cmake#L278) for it and it is [disabled explicitly](https://github.com/fluxer/katana/blob/master/packaging/archlinux/katanalibs/PKGBUILD#L54) on purpose in the package files because it defaults to `ON`.

**Comment by FredBezies** [comment] 2020-01-29 14:06
Noticed it. For my test, I switched it to ON. My bad. :man_facepalming:

**Comment by fluxer** [comment] 2020-01-29 14:12
No problem, perhaps the module should be bundled again to make it work out-of-the-box but I know some distributions use [qtchooser](https://aur.archlinux.org/packages/qtchooser) to workaround such issues so I intentionally left that to packagers instead of maintaining the CMake module and possibly macros file for Qt4 in the source tree.

**Comment by FredBezies** [comment] 2020-01-29 14:22
Ok. Try to build qca-qt4 against katie, cmake is shouting: "there is no qmake-qt4 !". Maybe a patch is needed when trying to build it with katie?

See: https://github.com/fluxer/katana/issues/22

**Comment by fluxer** [comment] 2020-01-31 16:25
Closing since the issue has been addressed.

Cheers!

**Closed by fluxer** 2020-01-31 16:25 UTC
